### ISSUE TITLE
年终总结投稿

### ISSUE THREAD

**Issue by Peter-JXL** [saveweb/review-2023#34]
博主姓名：PeterJXL
网站名字：从01开始
文章名字：2023年度总结
文章地址：https://www.peterjxl.com/About/summary-2023

期望出现在文档上的样式：[ PeterJXL 的 2023年度总结 ](https://www.peterjxl.com/About/summary-2023/)

本来打算通过PR的方式，但是 第三列 IA列不知道写什么，因此改为issue

**Comment by taranakineko** [comment]
第三列填写在互联网存档上的地址，例如 [Internet Archive](https://web.archive.org) 或者 [Archive Today](https://archive.today)
