### ISSUE TITLE
希望不要乱序展示

### ISSUE THREAD

**Issue by eryajf** [saveweb/review-2023#45]
如题，对于想要逐篇阅读的人而言，每次打乱顺序，简直是一个灾难。

**Comment by yzqzss** [comment]
乱序输出是尽量让每篇博文得到相似的曝光机会。
如果需要顺序读，可以看 https://github.com/saveweb/review-2023/blob/main/metadata.md
我们会把新加的放在底部。

**Comment by eryajf** [comment]
OK，了解了
