### ISSUE TITLE
排版混乱

### ISSUE THREAD

**Issue by SekaiMoe** [saveweb/review-2023#5]
![Screenshot_2023-12-25-15-40-02-80_df198e732186825c8df26e3c5a10d7cd](https://github.com/saveweb/review-2023/assets/153579552/74de555e-365e-4ee5-abc1-4d87996a7e04)
没人修一下吗(恼)

**Comment by taranakineko** [comment]
罪魁祸首表示修好了 ~~，下次不用 mt 管理器编辑文件了（~~

https://github.com/saveweb/review-2023/commit/3689cf1a8368ee833b7a96bac1b429085939437e
